name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update commit log
        run: |
          echo "Last commit generated on $(date)" > commit.log
          
      - name: Commit and push changes
        run: |
          git config --global user.name "phy0n"
          git config --global user.email "phionutsss@proton.me"

          MESSAGES=("Update commit logs" "Refactor code structure" "Fix minor bug" "Update documentation" "Chore: routine update")
          RANDOM_MSG=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}
          
          git add commit.log
          git commit -m "$RANDOM_MSG - $(date +'%Y-%m-%d')" || exit 0
          git push
